export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS'
export const USER_INFO_FAIL = 'USER_INFO_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_BY_ID_REQUEST = 'USER_BY_ID_REQUEST'
export const USER_BY_ID_SUCCESS = 'USER_BY_ID_SUCCESS'
export const USER_BY_ID_FAIL = 'USER_BY_ID_FAIL'

export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST'
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS'
export const SEARCH_USER_FAIL = 'SEARCH_USER_FAIL'
export const SEARCH_USER_RESET = 'SEARCH_USER_RESET'

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST'
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS'
export const USER_UNFOLLOW_FAIL = 'USER_UNFOLLOW_FAIL'

export const CHECK_USERNAME_REQUEST = 'CHECK_USERNAME_REQUEST'
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS'
export const CHECK_USERNAME_FAIL = 'CHECK_USERNAME_FAIL'

export const GET_FOLLOWING_REQUEST = 'GET_FOLLOWING_REQUEST'
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS'
export const GET_FOLLOWING_FAIL = 'GET_FOLLOWING_FAIL'

export const GET_FOLLOWERS_REQUEST = 'GET_FOLLOWERS_REQUEST'
export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS'
export const GET_FOLLOWERS_FAIL = 'GET_FOLLOWERS_FAIL'
